name: build-and-deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: containerregistory2.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker buildx build . -t containerregistory2.azurecr.io/myapp:${{ github.sha }}
          docker push containerregistory2.azurecr.io/myapp:${{ github.sha }}
